apiVersion: v1
kind: Service
metadata:
  name: luis-mencia-service
  namespace: luis-mencia-namespace
  labels:
    app: authentication-service
    version: "1.0"
spec:
  type: ClusterIP
  selector:
    app: authentication-service
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  sessionAffinity: ClientIP
