apiVersion: v1
kind: Secret
metadata:
  name: luis-mencia-secret
  namespace: luis-mencia-namespace
  labels:
    app: authentication-service
type: Opaque
stringData:
  # Configuración de base de datos PostgreSQL (Neon)
  DATABASE_URL: "r2dbc:postgresql://ep-plain-sound-a14svv9-pooler.us-east-1.aws.neon.tech:5432/ms-authenticationService?sslmode=require&preparedStatementCacheQueries=0&connectTimeout=30000"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_HFo2ij7rgRbN"
  
  # Configuración JWT
  JWT_SECRET: "your-secret-key-here-min-256-bits-change-in-production-please-use-a-secure-random-string-for-production"
  JWT_EXPIRATION: "3600000"
  JWT_REFRESH_EXPIRATION: "86400000"
  
  # Puerto de la aplicación
  PORT: "5002"
